package com.android.sample.home

import com.android.sample.Chat.ChatUIModel

/**
 * Immutable snapshot of everything the HomeScreen needs to render at a given time. Any UI change
 * produces a new instance via copy(...).
 */
data class HomeUiState(
    val userName: String = "Student",
    val isGuest: Boolean = false,
    val profile: com.android.sample.profile.UserProfile? = null,
    val systems: List<SystemItem> = emptyList(),
    val messages: List<ChatUIModel> = emptyList(),
    val messageDraft: String = "",
    val streamingMessageId: String? = null,
    val streamingSequence: Int = 0,
    val isDrawerOpen: Boolean = false,
    val isTopRightOpen: Boolean = false,
    val isLoading: Boolean = false,
    val showDeleteConfirmation: Boolean = false,
    val showGuestProfileWarning: Boolean = false,
    val isSending: Boolean = false,
    val conversations: List<com.android.sample.conversations.Conversation> = emptyList(),
    val currentConversationId: String? = null,
    val isOffline: Boolean = false,
    val showOfflineMessage: Boolean = false,
    val pendingAction: PendingAction? = null,
    val edPostResult: EdPostResult? = null,
    val edPostCards: List<EdPostCard> = emptyList(),
    val edPostsCards: List<EdPostsCard> =
        emptyList(), // Cards for fetched posts, associated with messages
    val isPostingToEd: Boolean = false,
    val edPostsState: EdPostsUiState = EdPostsUiState(stage = EdPostsStage.IDLE),
    val edCourses: List<EdCourse> = emptyList(),
    val isLoadingEdCourses: Boolean = false
)

/** Represents an EPFL system (e.g., IS-Academia, Moodle, Drive) and its connection state. */
data class SystemItem(val id: String, val name: String, val isConnected: Boolean)

/**
 * Legacy timeline entry used before migrating to message-based chat. Kept temporarily for backward
 * compatibility in tests or old screens.
 */
data class ActionItem(val id: String, val title: String, val time: String)

/** Sealed class for pending actions that require user interaction. */
sealed class PendingAction {
  /**
   * Represents a pending post to ED Discussion.
   *
   * @param draftTitle The formatted title for the post (generated by Apertus)
   * @param draftBody The formatted question body for the post (generated by Apertus)
   * @param messageId The ID of the AI message that generated this intent (for associating EdCard)
   */
  data class PostOnEd(
      val draftTitle: String,
      val draftBody: String,
      val messageId: String? = null
  ) : PendingAction()
}

/** Outcome of an ED post flow to drive UI banners. */
sealed class EdPostResult {
  data class Published(val title: String, val body: String) : EdPostResult()

  data object Cancelled : EdPostResult()

  data class Failed(val message: String) : EdPostResult()
}

/** Card model shown in chat after ED post flow completes. */
data class EdPostCard(
    val id: String,
    val title: String,
    val body: String,
    val status: EdPostStatus,
    val createdAt: Long
)

enum class EdPostStatus {
  Published,
  Cancelled
}

/** Card model for fetched ED posts, displayed after the message that generated them. */
data class EdPostsCard(
    val id: String,
    val messageId: String, // ID of the message that generated this card
    val query: String, // Original query used to fetch posts
    val posts: List<EdPost>,
    val filters: EdIntentFilters,
    val stage: EdPostsStage,
    val errorMessage: String? = null,
    val createdAt: Long
)

/** Represents a single ED Discussion post. */
data class EdPost(
    val title: String,
    val content: String,
    val date: Long,
    val author: String,
    val url: String
)

/** UI state for the ED Posts section. */
data class EdPostsUiState(
    val stage: EdPostsStage,
    val posts: List<EdPost> = emptyList(),
    val filters: EdIntentFilters = EdIntentFilters(),
    val errorMessage: String? = null
)

/** Stage of the ED Posts loading/display process. */
enum class EdPostsStage {
  IDLE,
  LOADING,
  EMPTY,
  ERROR,
  SUCCESS
}

/** Filters for ED posts search. */
data class EdIntentFilters(val course: String? = null)
