package com.android.sample.home

import com.android.sample.Chat.ChatUIModel

/**
 * Immutable snapshot of everything the HomeScreen needs to render at a given time. Any UI change
 * produces a new instance via copy(...).
 */
data class HomeUiState(
    val userName: String = "Student",
    val isGuest: Boolean = false,
    val profile: com.android.sample.profile.UserProfile? = null,
    val systems: List<SystemItem> = emptyList(),
    val messages: List<ChatUIModel> = emptyList(),
    val messageDraft: String = "",
    val streamingMessageId: String? = null,
    val streamingSequence: Int = 0,
    val isDrawerOpen: Boolean = false,
    val isTopRightOpen: Boolean = false,
    val isLoading: Boolean = false,
    val showDeleteConfirmation: Boolean = false,
    val showGuestProfileWarning: Boolean = false,
    val isSending: Boolean = false,
    val conversations: List<com.android.sample.conversations.Conversation> = emptyList(),
    val currentConversationId: String? = null,
    val isOffline: Boolean = false,
    val showOfflineMessage: Boolean = false,
    val pendingAction: PendingAction? = null
)

/** Represents an EPFL system (e.g., IS-Academia, Moodle, Drive) and its connection state. */
data class SystemItem(val id: String, val name: String, val isConnected: Boolean)

/**
 * Legacy timeline entry used before migrating to message-based chat. Kept temporarily for backward
 * compatibility in tests or old screens.
 */
data class ActionItem(val id: String, val title: String, val time: String)

/** Sealed class for pending actions that require user interaction. */
sealed class PendingAction {
  /**
   * Represents a pending post to ED Discussion.
   *
   * @param draftTitle The formatted title for the post (generated by Apertus)
   * @param draftBody The formatted question body for the post (generated by Apertus)
   */
  data class PostOnEd(val draftTitle: String, val draftBody: String) : PendingAction()
}
