package com.android.sample.Chat

import com.android.sample.home.SourceMeta

/**
 * Speaker role for a chat message.
 * - [USER]: message sent by the user.
 * - [AI]: message generated by the assistant.
 */
enum class ChatType {
  USER,
  AI
}

/**
 * UI model for a single chat message.
 *
 * This is a presentation-layer model for Compose. It encodes who spoke, the display text, when it
 * was produced, and an optional flag for a “still generating” placeholder.
 *
 * @property id Stable unique ID (UUID recommended). Use as the LazyColumn `key`.
 * @property text Display text of the message (already formatted for UI if needed).
 * @property timestamp Epoch millis (System.currentTimeMillis) for ordering/labels.
 * @property type Speaker role (USER/AI) to drive alignment and styling.
 * @property isThinking True if this represents a “thinking/placeholder” entry.
 */
data class ChatUIModel(
    val id: String,
    val text: String,
    val timestamp: Long,
    val type: ChatType,
    val isThinking: Boolean = false,
    val source: SourceMeta? = null
)
